# Generated by Django 4.2.7 on 2024-01-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_delete_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['created'], 'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
    ]
